apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pvc
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-storage-cls
  hostPath:
    path: /path/on/host
