apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: developeriq-pod-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: developeriq-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: "2023-01-01T00:00:10Z"
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0