apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment-green
  namespace: developeriq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-deployment-green
  template:
    metadata:
      labels:
        app: analytics-deployment-green
    spec:
      containers:
      - name: analytics
        image: 337689099048.dkr.ecr.ap-southeast-1.amazonaws.com/developeriq_be:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 150m
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: developeriq-secrets
              key: DB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service-green
  namespace: developeriq
  labels:
    app: analytics-deployment-green
spec:
  selector:
    app: analytics-deployment-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP