name: ECR Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.4'
      id: install
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Update  Kube Config
      run: aws eks update-kubeconfig --name developeriq_eks --region ap-southeast-1

    - name: Deploy
      run: |
        kubectl apply -f data-collector/deployment.yaml
        kubectl apply -f data-processor/deployment.yaml
        kubectl apply -f persistStorage.yaml
        kubectl apply -f prometheus.yaml
        kubectl apply -f grafana.yaml
        kubectl apply -f podScaling.yaml
        kubectl apply -f ingress.yaml
  